Config = {}

Config.donloc = {
    { x = -238.77, y = 767.75, z = 118.08 }
}

Config.tier1 = {
    "WEAPON_REVOLVER_SCHOFIELD",
    "WEAPON_REVOLVER_NAVY",
    "WEAPON_SHOTGUN_PUMP",
    "WEAPON_PISTOL_MAUSER",
    "WEAPON_PISTOL_SEMIAUTO",
    "WEAPON_REPEATER_WINCHESTER",
    "WEAPON_REPEATER_EVANS",
    "WEAPON_SHOTGUN_REPEATING",
    "WEAPON_RIFLE_SPRINGFIELD",
    "WEAPON_REVOLVER_LEMAT",
    "WEAPON_REPEATER_HENRY",
    "WEAPON_SHOTGUN_SAWEDOFF",
    "WEAPON_MELEE_MACHETE_COLLECTOR"
}


Config.tier2 = {
    "WEAPON_REVOLVER_CATTLEMAN",
    "WEAPON_MELEE_KNIFE_JAWBONE",
    "WEAPON_REPEATER_HENRY",
    "WEAPON_REPEATER_CARBINE",
    "WEAPON_SHOTGUN_DOUBLEBARREL",
    "WEAPON_REVOLVER_DOUBLEACTION",
    "WEAPON_MELEE_MACHETE_COLLECTOR",
    "WEAPON_RIFLE_VARMINT",
    "WEAPON_REVOLVER_LEMAT",
    "WEAPON_SHOTGUN_SAWEDOFF",
    "WEAPON_RIFLE_SPRINGFIELD",
    "WEAPON_SHOTGUN_REPEATING",
    "WEAPON_PISTOL_MAUSER",
    "WEAPON_REPEATER_EVANS"
}

Config.rareitem = {
    "WEAPON_PISTOL_M1899",
    "WEAPON_RIFLE_BOLTACTION",
    "WEAPON_SNIPERRIFLE_ROLLINGBLOCK",
    "w_rifle_rollingblock01",
    "WEAPON_SHOTGUN_SEMIAUTO",
    "WEAPON_MELEE_KNIFE_JAWBONE",
    "WEAPON_REVOLVER_LEMAT",
    "WEAPON_RIFLE_SPRINGFIELD",
    "WEAPON_REVOLVER_NAVY",
    "WEAPON_REPEATER_EVANS"
}

Config.webhookavatar = "https://cdn3.iconfinder.com/data/icons/hand/500/Hand_give_thumbs_finger-512.png"
Config.webhook = "https://discord.com/api/webhooks/965250230666813533/tWWIX40cQ4NU7cxzAuTFEg_Rq4AtmhZy7Y5WN-Uzn8quD51IABxLTovD88VV55ePd2G1"
Config.discordid = true -- turn to true if ur using discord whitelist 
