Config = {}	

Config.Locale = 'en'
--goldnuggetjob--
Config.info1             = 'Mencari goldnugget.'
Config.info2             = 'Mencari goldnugget..'
Config.info3             = 'Mencari goldnugget...'
Config.berhasil          = 'Anda menemukan beberapa goldnugget.'
Config.tidakberhasil     = 'Anda tidak menemukan apapun.'
Config.no_akses           = 'Anda tidak bisa mengambil goldnugget disini.'

--deliveryjob--

--hunting--
Config.Language = {
    ["NotHoldingAnimal"] = "Anda tidak memegang binatang",
    ["NotInTheButcher"] = "Saya tidak akan membeli hewan itu",
    ["AnimalSold"] = "Terima kasih atas kesepakatannya!",
    --notabutcher = "Anda Tidak Memiliki Pekerjaan yang Benar",
}

Config.ItemQuantity = {
    ["Max"] = 2,
    ["Min"] = 1
}

Config.aiButcherped = true -- spawn ai butched ped set to false if you dont want an ai butcher ped to spawn 
Config.joblocked = false -- lock the butcher so only people with the job can access. u can change access to each butcher by editing this  ["butcherjob"] = "butcher"
Config.maxpelts = 5 -- max pelts allowed on back of horse

Config.Butchers = {
    {["butchername"] = "Valentine Butcher", ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-339.0141, 767.6358, 115.5645),    ["heading"] = 100.41544342041,   ["radius"] = 3.0},
    {["butchername"] = "Strawberry Butcher", ["butcherjob"] = "butcher",   ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-1753.143, -392.4201, 155.2578),   ["heading"] = 181.37438964844,   ["radius"] = 3.0},
    {["butchername"] = "Saint denis",        ["butcherjob"] = "butcher",   ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(2819.622, -1331.547, 45.50584),   ["heading"] = 50.955146789551,   ["radius"] = 3.0},
    {["butchername"] = "Blackwater Butcher", ["butcherjob"] = "butcher",   ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-753.02, -1284.96, 43.27),    ["heading"] = 271.18,   ["radius"] = 3.0},
    {["butchername"] = "Annesburg Butcher", ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(2934.51, 1301.159, 43.48365),      ["heading"] = 70.572128295898,   ["radius"] = 3.0},
    {["butchername"] = "Van Horn Butcher",  ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(2991.844, 572.0218, 43.36182),     ["heading"] = 259.52850341797,   ["radius"] = 3.0},
    {["butchername"] = "Rhodes Butcher",   ["butcherjob"] = "butcher",     ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(1297.578, -1277.589, 74.88102),    ["heading"] = 146.60472106934,   ["radius"] = 3.0},
    {["butchername"] = "Armadillo Butcher", ["butcherjob"] = "butcher",    ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-3691.438, -2623.152, -14.75121),  ["heading"] = 0.46632757782936,  ["radius"] = 3.0},
    {["butchername"] = "Tumbleweed Butcher", ["butcherjob"] = "butcher",   ["pressToSell"] = "Press [~e~Space~q~] to sell",  ["blip"] = 1369919445,  ["npcmodel"] = "S_M_M_UNIBUTCHERS_01",  ["coords"] = vector3(-5510.371, -2947.005, -1.894515),  ["heading"] = 251.54911804199,   ["radius"] = 3.0}
}

-- to add more rewards on each animal edit the givenItem table. for example change ["givenItem"] ={ "meat"}, to ["givenItem"] ={ "meat","feathers"},
Config.Animals = {
    -- Animals
    [-1124266369]  = {["name"] = "Bear",                      ["givenItem"] ={ ""},      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 957520252,    ["good"] = 143941906,    ["perfect"] = 1292673537 },
    [-15687816381] = {["name"] = "Big Horn Ram",              ["givenItem"] ={ ""},      ["money"] = 0.4,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1796037447,   ["good"] = -476045512,   ["perfect"] = 1795984405 },
    [2028722809]   = {["name"] = "Boar",                      ["givenItem"] ={ ""},      ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1248540072,   ["good"] = nil,          ["perfect"] = -1858513856 },
    [-1963605336]  = {["name"] = "Buck",                      ["givenItem"] ={ ""},      ["money"] = 0.4,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1603936352,   ["good"] = -868657362,   ["perfect"] = -702790226 },
    [1556473961]   = {["name"] = "Bison",                     ["givenItem"] ={ ""},      ["money"] = 0.8,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -1730060063,  ["good"] = -591117838,   ["perfect"] = -237756948 },
    [1957001316]   = {["name"] = "Bull",                      ["givenItem"] ={ ""},      ["money"] = 0.6,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 9293261,      ["good"] = -336086818,   ["perfect"] = -53270317 },
    [1110710183]   = {["name"] = "Deer",                      ["givenItem"] ={ ""},      ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -662178186,   ["good"] = -1827027577,  ["perfect"] = -1035515486 },
    [-1003616053]  = {["name"] = "Duck",                      ["givenItem"] ={ ""},  ["money"] = 0.1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1459778951]   = {["name"] = "Eagle",                     ["givenItem"] ={ ""},  ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [831859211]    = {["name"] = "Egret",                     ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2021043433]  = {["name"] = "Elk",                       ["givenItem"] ={ ""},      ["money"] = 0.45,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 2053771712,   ["good"] = 1181652728,   ["perfect"] = -1332163079 },
    [252669332]    = {["name"] = "American Red Fox",          ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1647012424,   ["good"] = 238733925,    ["perfect"] = 500722008 },
    [-1143398950]  = {["name"] = "Big Grey Wolf",             ["givenItem"] ={ ""},      ["money"] = 0.9,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 85441452,     ["good"] = 1145777975,   ["perfect"] = 653400939 },
    [-885451903]   = {["name"] = "Medium Grey Wolf",          ["givenItem"] ={ ""},      ["money"] = 0.85,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 85441452,     ["good"] = 1145777975,   ["perfect"] = 653400939 },
    [-829273561]   = {["name"] = "Small Grey Wolf",           ["givenItem"] ={ ""},      ["money"] = 0.8,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 85441452,     ["good"] = 1145777975,   ["perfect"] = 653400939 },
    [1104697660]   = {["name"] = "Vulture",                   ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-407730502]   = {["name"] = "Snapping Turtle",           ["givenItem"] ={ ""},      ["money"] = 2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-466054788]   = {["name"] = "Wild Turkey",               ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2011226991]  = {["name"] = "Wild Turkey",               ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-166054593]   = {["name"] = "Wild Turkey",               ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-229688157]   = {["name"] = "Water Snake",               ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-229688157]   = {["name"] = "Water Snake",               ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1790499186]  = {["name"] = "Snake Red Boa",             ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1464167925]   = {["name"] = "Snake Fer-De-Lance",        ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [846659001]    = {["name"] = "Black-Tailed Rattlesnake",  ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [545068538]    = {["name"] = "Western Rattlesnake",       ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1211566332]  = {["name"] = "Striped Skunk",             ["givenItem"] ={ ""},      ["money"] = 0.1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [40345436]     = {["name"] = "Merino Sheep",              ["givenItem"] ={ ""},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1729948479,   ["good"] = -1317365569,  ["perfect"] = 1466150167 },
    [-164963696]   = {["name"] = "Herring Seagull",           ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1076508705]  = {["name"] = "Roseate Spoonbill",         ["givenItem"] ={ ""},  ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [2023522846]   = {["name"] = "Dominique Rooster",         ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-466687768]   = {["name"] = "Red-Footed Booby",          ["givenItem"] ={ ""},  ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-575340245]   = {["name"] = "Wester Raven",              ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1458540991]   = {["name"] = "North American Racoon",     ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-541762431]   = {["name"] = "Black-Tailed Jackrabbit",   ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1755643085]   = {["name"] = "American Pronghorn Doe",    ["givenItem"] ={ ""},      ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -983605026,   ["good"] = 554578289,    ["perfect"] = -1544126829 },
    [2079703102]   = {["name"] = "Greater Prairie Chicken",   ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1414989025]  = {["name"] = "Wirginia Possum",           ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1007418994]   = {["name"] = "Berkshire Pig",             ["givenItem"] ={ ""},      ["money"] = 0.35,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -308965548,   ["good"] = -57190831,    ["perfect"] = -1102272634 },
    [1416324601]   = {["name"] = "Ring-Necked Pheasant",      ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1265966684]   = {["name"] = "American White Pelican",    ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1797450568]  = {["name"] = "Blue And Yellow Macaw",     ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1654513481]   = {["name"] = "Panther",                   ["givenItem"] ={ ""},      ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1584468323,   ["good"] = -395646254,   ["perfect"] = 1969175294 },
    [1205982615]   = {["name"] = "Californian Condor",        ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2063183075]  = {["name"] = "Dominique Chicken",         ["givenItem"] ={ ""},  ["money"] = 0.15,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2073130256]  = {["name"] = "Double-Crested Cormorant",  ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [90264823]     = {["name"] = "Cougar",                    ["givenItem"] ={ ""},      ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1914602340,   ["good"] = 459744337,    ["perfect"] = -1791452194 },
    [-50684386]    = {["name"] = "Florida Cracker Cow",       ["givenItem"] ={ ""},  ["money"] = 1,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 334093551,    ["good"] = 1150594075,   ["perfect"] = -845037222 },
    [480688259]    = {["name"] = "Coyote",                    ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -1558096473,  ["good"] = 1150939141,   ["perfect"] = -794277189 },
    [-564099192]   = {["name"] = "Whooping Crane",            ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },   
    [457416415]    = {["name"] = "Gila Monster",              ["givenItem"] ={ ""},      ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-753902995]   = {["name"] = "Alpine Goat",               ["givenItem"] ={ ""},      ["money"] = 0.45,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 699990316,    ["good"] = 1710714415,   ["perfect"] = -1648383828 },
    [723190474]    = {["name"] = "Canada Goose",              ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-2145890973]  = {["name"] = "Ferruinous Hawk",           ["givenItem"] ={ ""},  ["money"] = 0.3,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1095117488]   = {["name"] = "Great Blue Heron",          ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1854059305]  = {["name"] = "Green Iguana",              ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-593056309]   = {["name"] = "Desert Iguana",             ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1751700893]   = {["name"] = "Peccary Pig",               ["givenItem"] ={ ""},      ["money"] = 0.35,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -99092070,    ["good"] = -1379330323,  ["perfect"] = 1963510418 },
    [386506078]    = {["name"] = "Common Loon",               ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1098441944]  = {["name"] = "Moose",                     ["givenItem"] ={ ""},      ["money"] = 0.4,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1868576868,   ["good"] = 1636891382,   ["perfect"] = -217731719 },
    [-1134449699]  = {["name"] = "American Muskrat",          ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-861544272]   = {["name"] = "Great Horned Owl",          ["givenItem"] ={ ""},  ["money"] = 0.25,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [556355544]    = {["name"] = "Angus Ox",                  ["givenItem"] ={ ""},      ["money"] = 0.55,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 4623248928,   ["good"] = 1208128650,   ["perfect"] = 659601266 },
      [-1892280447]  = {["name"] = "Alligator",                 ["givenItem"] ={ ""},      ["money"] = 0.95,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1806153689,   ["good"] = -802026654,   ["perfect"] = -1625078531 },
    [759906147]    = {["name"] = "North American Beaver",     ["givenItem"] ={ ""},      ["money"] = 0.2,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -1569450319,  ["good"] = -2059726619,  ["perfect"] = 854596618 },
    [730092646]    = {["name"] = "American Black Bear",       ["givenItem"] ={ ""},      ["money"] = 0.85,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 1083865179,   ["good"] = 1490032862,   ["perfect"] = 663376218 },
    -- Fish
    [-711779521]   = {["name"] = "Longnose Gar",              ["givenItem"] ={ ""},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-1553593715]  = {["name"] = "Muskie",                    ["givenItem"] ={ ""},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [-300867788]   = {["name"] = "Lake Sturgeon",             ["givenItem"] ={ ""},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [1538187374]   = {["name"] = "Channel Catfish",           ["givenItem"] ={ ""},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
    [697075200]    = {["name"] = "Northern Pike",             ["givenItem"] ={ ""},      ["money"] = 0.5,  ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = nil,          ["good"] = nil,          ["perfect"] = nil },
	[-1892280448]  = {["name"] = "Alligator big",             ["givenItem"] ={ ""},      ["money"] = 10, ["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = -1243878166,   ["good"] = -802026654,   ["perfect"] = -1475338121 },
    [-368368059]   = {["name"] = "Bullgator Legendary",       ["givenItem"] ={ ""},      ["money"] = 10,["gold"] = 0,  ["rolPoints"] = 0,  ["xp"] = 3,  ["poorQualityMultiplier"] = 1.0,  ["goodQualityMultiplier"] = 1.5,  ["perfectQualityMultiplier"] = 2,  ["poor"] = 3926599237,   ["good"] = 3926599254,   ["perfect"] = -368368054 },


}

--mining--
Config.MinSwing = 1 -- Min Swings on a Rock
Config.MaxSwing = 3 -- Max Swings on a Rock

Config.Pickaxe = "pickaxe" -- Item from your database that you want to use for a pickaxe
Config.MinGoldChance = 1 -- Minimum Gold Chance
Config.MaxGoldChance = 2 -- Maximum Gold Chance

Config.GoldChance = 2 -- 2% chance to find a goldnugget (make sure is between MinGoldChance and MaxGoldChance)

Config.MinePromptKey = 0xD9D0E1C0 -- Key used to start Mining (Spacebar)
Config.StopMiningKey = 0x3B24C470 -- Key to stop Mining (F)
Config.MineRockKey = 0x07B8BEAF -- Key to Mine Rock (Left Click)

Config.Items = {
    "clay",
	"provision_coal",
	"copper",
	"iron",
	"sulfur",
	"stone"
}

Config.Rocks = {
    'bgv_rock_scree_sim_09',
    'old_hen_rock_scree_sim_08',
    's_gry_rock01x',
    'tal_rock_scree_sim_11',
    'dak_rock_scree_stg345_sim_02',
    'gri_rock_scree_sim_08',
    'hea_rock_scree_sim_10',
    'tal_rock_scree_sim_03',
    'cumb_rock_scree_sim_06',
    'old_hen_rock_scree_sim_11',
    'tal_rock_scree_sim_05',
    'hea_rock_scree_sim_09',
    'bgv_rock_scree_sim_11',
    'cumb_rock_scree_sim_11',
    'mp_roa_rock_grp_l_03',
    's_gri_rock_s_03',
    'sca_rock_scree_sim_04',
    'gri_rock_scree_sim_09',
    'sca_rock_scree_sim_01',
    'old_hen_rock_scree_sim_06',
    'gua_rock_scree_sim_03',
    'tal_rock_scree_sim_07',
    'bgv_rock_scree_sim_04',
    'sca_rock_scree_sim_09',
    'gri_rock_scree_sim_11',
    'bgv_rock_scree_sim_03',
    'dak_rock_scree_stg345_sim_03',
    'gri_rock_scree_sim_02',
    'gri_rock_scree_sim_02',
    'grp_rock_scree_sim_02',
    'grp_rock_scree_sim_10',
    'bgv_rock_scree_sim_06',
    'cumb_rock_scree_sim_10',
    'cumb_rock_scree_sim_04',
    'mp005_p_mp_rock_stash01',
    'sca_rock_scree_sim_08',
    'grp_rock_scree_sim_04',
    'grp_rock_scree_sim_06',
    'roa_rock_scree_sim_08',
    'hea_rock_scree_sim_05',
    'dak_rock_scree_stg345_sim_09',
    'bgv_rock_scree_sim_10',
    'old_hen_rock_scree_sim_04',
    'sca_rock_scree_sim_05',
    'hea_rock_scree_sim_03',
    'tal_rock_scree_sim_01',
    'old_hen_rock_scree_sim_05',
    'vfx_scree_rock_01',
    'tal_rock_scree_sim_06',
    'roa_rock_scree_sim_11',
    'tal_rock_scree_sim_08',
    'bgv_rock_scree_sim_01',
    'sca_rock_scree_sim_03',
    'sca_rock_scree_sim_10',
    'p_int_rockhang03x',
    'old_hen_rock_scree_sim_01',
    'roa_rock_scree_sim_09',
    'hea_rock_scree_sim_11',
    'hea_rock_scree_sim_02',
    'hea_rock_scree_sim_07',
    'grp_rock_scree_sim_09',
    'gua_rock_scree_sim_06',
    'old_hen_rock_scree_sim_10',
    'tal_rock_scree_sim_02',
    's_gri_rock_l_03',
    's_gri_rock_m_03',
    'mp_big_rock_scan_07',
    'cumb_rock_scree_sim_077',
    'roa_rock_scree_sim_01',
    'mp_p_rock_mssgry_lrg_b',
    'mp_sca_rock_grp_l_02',
    'bgv_rock_scree_sim_08',
    'alp_rock_scree_sim_08',
    'grp_rock_scree_sim_01',
    'alp_rock_scree_sim_04',
    'hea_rock_scree_sim_08',
    'tal_rock_scree_sim_04',
    'alp_rock_scree_sim_07',
    'gua_rock_scree_sim_01',
    'bgv_rock_scree_sim_02',
    'dak_rock_scree_stg345_sim_01',
    'p_rock_stash01',
    'gri_rock_scree_sim_01',
    'dak_rock_scree_stg345_sim_04',
    'roa_rock_scree_sim_06',
    'old_hen_rock_scree_sim_09',
    'gua_rock_scree_sim_02',
    'dak_rock_scree_stg345_sim_08',
    'alp_rock_scree_sim_02',
    'cumb_rock_scree_sim_03',
    'roa_rock_scree_sim_07',
    'cumb_rock_scree_sim_02',
    'old_hen_rock_scree_sim_02',
    'alp_rock_scree_sim_01',
    'bgv_rock_scree_sim_05',
    'cumb_rock_scree_sim_09',
    'roa_rock_scree_sim_04',
    'sca_rock_scree_sim_07',
    'gri_rock_scree_sim_04',
    'cumb_rock_scree_sim_08',
    'tal_rock_scree_sim_09',
    'alp_rock_scree_sim_03',
    'alp_rock_scree_sim_09',
    'alp_rock_scree_sim_10',
    'sca_rock_scree_sim_11',
    'hea_rock_scree_sim_04'
}
--lumberjack--
Config.Axe = "hatchet" -- Item you want to use as an axe

Config.ChopPromptKey = 0xD9D0E1C0 -- Key to press for prompt
Config.CancelChopKey = 0x3B24C470 -- Key to Cancel Choppinp
Config.ChopTreeKey = 0x07B8BEAF -- Key To Chop Tree

Config.MinSwing = 2
Config.MaxSwing = 3

Config.Trees = {
    --Birch
    "p_tree_birch_03",
    "p_tree_birch_03b",
    "p_tree_birch_03_lg",
    "p_tree_birch_03_md",
    "p_tree_birch_03_md_a",
    "p_tree_birch_04",
    "p_tree_birch_04_lg",
    "p_tree_birch_multistem",
    "p_tree_birch_tall_sap",
    "p_tree_poplar_01",
    "p_tree_poplar_02",
    "p_tree_riv_poplar_01",
    "p_tree_riv_poplar_02",
    "p_tree_willow_01",
    "p_tree_willow_02",
    "rdr2_tree_gimlet",
    "rdr2_tree_riverbirch",
    "rdr_nrml_branch_aa_sim",
    "p_tree_birch_01_sapling",
    "p_tree_birch_02_sapling",
    "p_tree_birch_03_sapling",
    "rdr2_tree_rata01",
    "rdr2_tree_rata02",
    --Cedars
    "p_sap_fir_aa_sim",
    "p_sap_fir_ab_sim",
    "p_sap_fir_ac_sim",
    "p_sap_fir_snow_aa_sim",
    "p_sap_fir_snow_ab_sim",
    "p_sap_fir_snow_ac_sim",
    "p_tree_cedar_03b_snow",
    "p_tree_cedar_03b_snow_deep",
    "p_tree_cedar_decor_01",
    "p_tree_cedar_decor_02",
    "p_tree_cedar_s_deep_02_c",
    "p_tree_douglasfir_01",
    "p_tree_douglasfir_02",
    "p_tree_douglasfir_03",
    "p_tree_douglasfir_04",
    "p_tree_douglasfir_05",
    "p_tree_douglasfir_snow_01",
    "p_tree_douglasfir_snow_01a",
    "p_tree_douglasfir_snow_02",
    "p_tree_douglasfir_snow_03",
    "p_tree_douglasfir_snow_03a",
    "p_tree_douglasfir_snow_03b",
    "p_tree_douglasfir_snow_03c",
    "p_tree_douglasfir_snow_03d",
    "p_tree_douglasfir_snow_04",
    "p_tree_douglasfir_snow_04a",
    "p_tree_douglasfir_snow_05",
    "p_tree_douglasfir_snow_05a",
    "p_tree_lodgepole_01",
    "p_tree_lodgepole_02",
    "p_tree_lodgepole_02_bv",
    "p_tree_lodgepole_02_bv_l",
    "p_tree_lodgepole_02_bv_s",
    "p_tree_lodgepole_03",
    "p_tree_lodgepole_04",
    "p_tree_lodgepole_05",
    "p_tree_lodgepole_06",
    "p_tree_lodgepole_07",
    "p_tree_lodgepole_07a",
    "p_tree_lodgepole_roots_01",
    "p_tree_lodgepole_snow_01",
    "p_tree_lodgepole_snow_01a",
    "p_tree_lodgepole_snow_02",
    "p_tree_lodgepole_snow_02a",
    "p_tree_lodgepole_snow_02b",
    "p_tree_lodgepole_snow_03",
    "p_tree_lodgepole_snow_04",
    "p_tree_longleafpine_01",
    "p_tree_longleafpine_02",
    "p_tree_longleafpine_03",
    "p_tree_longleafpine_04",
    "p_tree_pine_burnt_01",
    "p_tree_pine_burnt_01a",
    "p_tree_pine_burnt_02",
    "p_tree_pine_burnt_02a",
    "p_tree_pine_burnt_log_aa",
    "p_tree_pine_burnt_log_ab",
    "p_tree_pine_ponderosa_01",
    "p_tree_pine_ponderosa_02",
    "p_tree_pine_ponderosa_03",
    "p_tree_pine_ponderosa_04",
    "p_tree_pine_ponderosa_05",
    "p_tree_pine_ponderosa_06",
    "p_tree_pine_ponderosa_07",
    "p_tree_ponderosa_sap_01",
    "p_tree_ponderosa_sap_02",
    "p_tree_ponderosa_sap_03",
    "p_tree_whitepine_01",
    "p_tree_whitepine_02",
    "p_tree_whitepine_03",
    "p_tree_whitepine_04",
    "p_tree_whitepine_05",
    "p_tree_whitepine_06",
    "p_tree_whitepine_07",
    "p_tree_whitepine_08",
    "p_tree_whitepine_09",
    "p_tree_whitepine_10",
    "p_tree_whitepine_sap_01",
    "p_tree_whitepine_sap_02",
    "p_tree_whitepine_sap_03",
    "rdr_pine_branch_aa_sim",
    "rdr_pine_branch_ab_sim",
    "rdr2_tree_utahjuniper",
    --Dead
    "p_tree_engoak_dead",
    "p_tree_fallen_pine_01",
    "p_tree_fallen_pine_01bc",
    "p_tree_fallen_pine_02",
    "p_tree_lightning_01",
    "p_tree_lightning_02",
    "p_tree_lightning_03",
    "p_tree_lightning_04",
    "p_tree_maple_03_dead",
    "p_tree_pine_dead_01",
    "p_tree_pine_dead_02",
    "p_tree_riodel_01",
    "p_tree_rusolive_dead",
    "p_tree_rusolive_dead001",
    "p_tree_w_r_cedar_dead",
    "p_tree_w_r_cedar_dead_01",
    "p_tree_w_r_cedar_dead_02",
    "p_tree_mesquite_01",
    "p_tree_mesquite_01_dead",
    --Maples
    "p_tree_maple_dead_s_01",
    "p_tree_maple_02",
    "p_tree_maple_03",
    "p_tree_maple_03_lg",
    "p_tree_maple_03_lg_m",
    "p_tree_maple_03_lg_os",
    "p_tree_maple_03_md",
    "p_tree_maple_03_md_bv",
    "p_tree_maple_03_md_bv_l",
    "p_tree_maple_03_md_bv_s",
    "p_tree_maple_03_os",
    "p_tree_maple_04_md",
    "p_tree_maple_04_md_m",
    "p_tree_maple_05_lg",
    "p_tree_maple_05_lg_ch",
    "p_tree_maple_05_lg_ch2",
    "p_tree_maple_05_lg_m",
    "p_tree_maple_bent_01",
    "p_tree_maple_bent_02",
    "p_tree_maple_bent_03",
    "p_tree_maple_s_01",
    "p_tree_maple_s_02",
    "p_tree_maple_s_03",
    "p_tree_maple_s_04",
    "p_tree_mapleroot_01",
    "p_tree_mapleroot_02",
    "p_tree_riv_maple_01",
    "p_tree_riv_maple_04",
    "p_sap_maple_aa_sim",
    "p_sap_maple_ab_sim",
    "p_sap_maple_ac_sim",
    "p_sap_maple_ad_sim",
    "p_sap_maple_ba_sim",
    "p_sap_maple_bb_sim",
    "p_sap_maple_bc_sim",
    --Oaks
    "p_tree_angel_oak",
    "p_tree_blue_oak_01",
    "p_tree_cottonwood_01",
    "p_tree_cottonwood_02",
    "p_tree_cottonwood_03",
    "p_tree_cottonwood_04",
    "p_tree_engoak_01",
    "p_tree_engoak_01_lg",
    "p_tree_engoak_02",
    "p_tree_engoak_moss_01",
    "p_tree_engoak_moss_01_os",
    "p_tree_engoak_nbx_01",
    "p_tree_hangingtree_moss",
    "p_tree_hangingtreebranch",
    "p_tree_hangingtreeoak01",
    "p_tree_jacada_01",
    "p_tree_liveoak_01",
    "p_tree_liveoak_moss_01",
    "p_tree_oak_01",
    "p_tree_oak_braith_03",
    "p_tree_poor_joe_oak",
    "p_tree_white_oak_01",
    "p_tree_white_oak_01_ch",
    "p_tree_white_oak_02",
    "rdr2_tree_beech",
    "rdr2_tree_brokentree",
    "rdr2_tree_sycamore",
    --Palms
    "p_tree_bamboo_01",
    "p_tree_bamboo_01_crt",
    "p_tree_banana_01_crt",
    "p_tree_banana_01_md_crt",
    "p_tree_banana_01_lg",
    "p_tree_banana_dead_01_lg",
    "p_tree_banyan_01",
    "p_tree_magnolia_01",
    "p_tree_magnolia_02",
    "p_tree_magnolia_02_lg",
    "p_tree_magnolia_02_lg_os",
    "p_tree_magnolia_02_md",
    "p_tree_magnolia_02_vine",
    "p_tree_magnolia_03",
    "p_tree_magnolia_03_crt",
    "p_tree_magnolia_04",
    "p_tree_mangrove_02",
    "p_tree_mangrove_03",
    "p_tree_palm_fan_03a",
    "p_tree_palm_fan_04b",
    "p_tree_palm_fan_06",
    "p_tree_palm_fan_bea_03b",
    "p_tree_palm_fan_low_ba",
    "p_tree_palm_s_01a",
    "p_tree_palm_s_01d",
    "p_tree_palm_s_01e",
    "p_tree_palm_s_01f",
    "p_sap_magnolia_aa_sim",
    --Tall Trees
    "p_tree_log_redwood_01",
    "p_tree_redwood_05",
    "p_tree_redwood_05_lg",
    "p_tree_redwood_05_md",
    "p_tree_redwood_05_mf",
    "p_tree_redwood_05_sm",
    --Trees
    "p_tree_apple_01",
    "p_tree_burntstump_01",
    "p_tree_burntstump_03",
    "p_tree_hickory_01",
    "p_tree_hickory_02",
    "p_tree_orange_01",
    "p_tree_pine_newburnt_01",
    "p_tree_pine_newburnt_02",
    "p_tree_pine_newburnt_03",
    "p_tree_pine_newburnt_04",
    "p_tree_pine_newburnt_log_01",
    "p_tree_pine_newburnt_log_02",
    --Swamp
    "p_tree_baldcypress_01_dead",
    "p_tree_baldcypress_01a",
    "p_tree_baldcypress_01a_os",
    "p_tree_baldcypress_02",
    "p_tree_baldcypress_02_os",
    "p_tree_baldcypress_02_sm_a",
    "p_tree_baldcypress_03",
    "p_tree_baldcypress_03_dead",
    "p_tree_baldcypress_03_script",
    "p_tree_baldcypress_04_dead",
    "p_tree_baldcypress_04_sm_a",
    "p_tree_baldcypress_04a",
    "p_tree_baldcypress_05",
    "p_tree_baldcypress_05_sm_a",
    "p_tree_baldcypress_06a",
    "p_tree_baldcypress_06b",
    "p_tree_baldcypress_05a",
    "p_tree_baldcypress_07",
    "p_tree_baldcypress_grave",
    "p_tree_baldcypress_knees_01",
    "p_tree_baldcypress_knees_02",
    "p_tree_branch_01_swamp",
    "p_tree_branch_02_swamp",
    "p_tree_log_01_swamp",
    "p_tree_log_01_swamp_sim",
    "p_tree_stump_01_swamp",
    "p_tree_stump_02_swamp",
    "p_sap_cypress_aa_sim",
    "p_sap_cypress_ab_sim",
}